#version 450

#include "generic_head.glsl"
#include "types.glsl"

#extension GL_EXT_control_flow_attributes : enable

#define FLT_MAX 3.402823466e+38F

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer A {A_TYPE data_a[];};
layout (binding = 1) writeonly buffer D {D_TYPE data_d[];};

layout (constant_id = 0) const uint BLOCK_SIZE = 32;

shared FLOAT_TYPE tmpmax[BLOCK_SIZE];
shared uint tmp[BLOCK_SIZE];
#ifdef FIRST_MAX
shared uint tmpinvalid[BLOCK_SIZE];
#endif

void main() {
    const uint row = gl_WorkGroupID.z * 262144 + gl_WorkGroupID.y * 512 + gl_WorkGroupID.x;
    const uint col = gl_LocalInvocationID.x;

    if (row >= p.KY) {
        return;
    }

    A_TYPE amax = -FLT_MAX;
    uint acol = col;
#ifdef FIRST_MAX
    bool invalid = false;
#endif

    if (col < p.KX) {
        amax = data_a[row*p.KX + col];
#ifdef FIRST_MAX
        invalid = isnan(amax) || isinf(amax);
#endif
    }

    for (uint i = col + BLOCK_SIZE; i < p.KX; i += BLOCK_SIZE) {
        A_TYPE val = data_a[row*p.KX + i];
#ifdef FIRST_MAX
        invalid = invalid || isnan(val) || isinf(val);
#endif
        if (val > amax) {
            amax = val;
            acol = i;
        }
    }

    tmp[col] = acol;
    tmpmax[col] = amax;
#ifdef FIRST_MAX
    tmpinvalid[col] = invalid ? 1 : 0;
#endif

    barrier();
    [[unroll]] for (int s = int(BLOCK_SIZE) / 2; s > 0; s >>= 1) {
        if (col < s && col + s < p.KX) {
#ifdef FIRST_MAX
            tmpinvalid[col] |= tmpinvalid[col + s];
#endif
            if (tmpmax[col] < tmpmax[col + s]
#ifdef FIRST_MAX
                || (tmpmax[col] == tmpmax[col + s] && tmp[col + s] < tmp[col])
#else
                || (tmpmax[col] == tmpmax[col + s] && tmp[col + s] > tmp[col])
#endif
            ) {
                tmpmax[col] = tmpmax[col + s];
                tmp[col] = tmp[col + s];
            }
        }
        barrier();
    }

    if (col == 0) {
#ifdef FIRST_MAX
        data_d[row] = tmpinvalid[0] != 0 ? D_TYPE(-1) : D_TYPE(tmp[0]);
#else
        data_d[row] = D_TYPE(tmp[0]);
#endif
    }
}
